/**
 * This file is autogenerated by scripts/generate-nextjs-deployedContracts.js
 * Do not edit manually. Run "yarn deploy" in packages/hardhat to regenerate.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
